import esbuild from 'esbuild';
import process from 'process';
import { builtinModules, createRequire } from 'node:module';
import fs from 'fs';
import path from 'path';

const require = createRequire(import.meta.url);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const dev = process.argv[2] === 'development';

const wasmPlugin = {
    name: 'wasm-binary',
    setup(build) {
        build.onResolve({ filter: /\.wasm$/ }, (args) => {
            const resolved = require.resolve(args.path, {
                paths: [args.resolveDir],
            });
            return { path: resolved, namespace: 'wasm-binary' };
        });
        build.onLoad(
            { filter: /.*/, namespace: 'wasm-binary' },
            async (args) => ({
                contents: await fs.promises.readFile(args.path),
                loader: 'binary',
            }),
        );
    },
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    plugins: [wasmPlugin],
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtinModules,
    ],
    format: 'cjs',
    target: 'es2021',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: prod,
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else if (dev) {
    await context.rebuild();
    // copy the generated file to the plugin folder
    fs.copyFileSync(
        'main.js',
        './test-vault/.obsidian/plugins/vim-motions/main.js',
    );
    fs.copyFileSync(
        'manifest.json',
        './test-vault/.obsidian/plugins/vim-motions/manifest.json',
    );
    fs.copyFileSync(
        'styles.css',
        './test-vault/.obsidian/plugins/vim-motions/styles.css',
    );
    process.exit(0);
} else {
    await context.watch();
}
