export interface TestCaseDefinition {
    name: string;
    content: string;
    cursor: { line: number; ch: number };
    keys: string;
    luaSetup?: string;
}

export interface SuiteDefinition {
    name: string;
    nvimSetup?: string[];
    cases: TestCaseDefinition[];
}

export const SUITES: SuiteDefinition[] = [
    {
        name: 'normal-motions',
        cases: [
            {
                name: 'h should move cursor left',
                content: 'abcdef',
                cursor: { line: 0, ch: 3 },
                keys: 'h',
            },
            {
                name: 'l should move cursor right',
                content: 'abcdef',
                cursor: { line: 0, ch: 1 },
                keys: 'l',
            },
            {
                name: 'j should move cursor down',
                content: 'line1\nline2\nline3',
                cursor: { line: 0, ch: 0 },
                keys: 'j',
            },
            {
                name: 'k should move cursor up',
                content: 'line1\nline2\nline3',
                cursor: { line: 2, ch: 0 },
                keys: 'k',
            },
            {
                name: '3j should move 3 lines down',
                content: 'a\nb\nc\nd\ne',
                cursor: { line: 0, ch: 0 },
                keys: '3j',
            },
            {
                name: 'w should move to next word start',
                content: 'hello world foo',
                cursor: { line: 0, ch: 0 },
                keys: 'w',
            },
            {
                name: 'b should move to previous word start',
                content: 'hello world foo',
                cursor: { line: 0, ch: 8 },
                keys: 'b',
            },
            {
                name: 'e should move to end of word',
                content: 'hello world foo',
                cursor: { line: 0, ch: 0 },
                keys: 'e',
            },
            {
                name: 'W should move to next WORD start',
                content: 'hello-world foo',
                cursor: { line: 0, ch: 0 },
                keys: 'W',
            },
            {
                name: 'B should move to previous WORD start',
                content: 'foo hello-world bar',
                cursor: { line: 0, ch: 15 },
                keys: 'B',
            },
            {
                name: 'E should move to end of WORD',
                content: 'hello-world foo',
                cursor: { line: 0, ch: 0 },
                keys: 'E',
            },
            {
                name: 'ge should move to end of previous word',
                content: 'hello world foo',
                cursor: { line: 0, ch: 6 },
                keys: 'ge',
            },
            {
                name: '2w should move 2 words forward',
                content: 'one two three four',
                cursor: { line: 0, ch: 0 },
                keys: '2w',
            },
            {
                name: 'w across empty lines',
                content: 'one\n\n\nfour',
                cursor: { line: 0, ch: 0 },
                keys: 'w',
            },
            {
                name: 'w with punctuation boundary',
                content: 'word.other',
                cursor: { line: 0, ch: 0 },
                keys: 'w',
            },
            {
                name: 'w should wrap to next line',
                content: 'one\ntwo',
                cursor: { line: 0, ch: 2 },
                keys: 'w',
            },
            {
                name: 'b at start of document should not move',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'b',
            },
            {
                name: 'w from punctuation to next word',
                content: 'word.other',
                cursor: { line: 0, ch: 4 },
                keys: 'w',
            },
            {
                name: 'b should stop at punctuation boundary',
                content: 'word.other',
                cursor: { line: 0, ch: 5 },
                keys: 'b',
            },
            {
                name: 'ge across line boundary',
                content: 'one\ntwo',
                cursor: { line: 1, ch: 0 },
                keys: 'ge',
            },
            {
                name: 'e should cross line boundary',
                content: 'one\ntwo',
                cursor: { line: 0, ch: 2 },
                keys: 'e',
            },
            {
                name: '0 should move to first column',
                content: '  hello world',
                cursor: { line: 0, ch: 5 },
                keys: '0',
            },
            {
                name: '$ should move to end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: '$',
            },
            {
                name: '^ should move to first non-blank',
                content: '   hello world',
                cursor: { line: 0, ch: 0 },
                keys: '^',
            },
            {
                name: '_ should move to first non-blank',
                content: '  one\n  two\n  three',
                cursor: { line: 0, ch: 0 },
                keys: '_',
            },
            {
                name: '$ with count',
                content: 'one\ntwo\nthree',
                cursor: { line: 0, ch: 0 },
                keys: '2$',
            },
            {
                name: '+ should move to next line non-blank',
                content: '  one\n  two\n  three',
                cursor: { line: 0, ch: 0 },
                keys: '+',
            },
            {
                name: '- should move to prev line non-blank',
                content: '  one\n  two\n  three',
                cursor: { line: 2, ch: 4 },
                keys: '-',
            },
            {
                name: 'G should move to last line',
                content: 'one\ntwo\nthree\nfour\nfive',
                cursor: { line: 0, ch: 0 },
                keys: 'G',
            },
            {
                name: 'gg should move to first line',
                content: 'one\ntwo\nthree\nfour\nfive',
                cursor: { line: 4, ch: 0 },
                keys: 'gg',
            },
            {
                name: '3G should move to line 3',
                content: 'one\ntwo\nthree\nfour\nfive',
                cursor: { line: 0, ch: 0 },
                keys: '3G',
            },
            {
                name: '5gg should move to line 5',
                content: 'a\nb\nc\nd\ne\nf\ng',
                cursor: { line: 0, ch: 0 },
                keys: '5gg',
            },
            {
                name: '| should move to column 1',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: '|',
            },
            {
                name: '5| should move to column 5',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: '5|',
            },
            {
                name: 'w through markdown formatting',
                content: '**bold** and *italic* text',
                cursor: { line: 0, ch: 0 },
                keys: 'wwww',
            },
            {
                name: 'f should find char past formatting marks',
                content: '**hello** world',
                cursor: { line: 0, ch: 0 },
                keys: 'fw',
            },
            {
                name: 'e through inline code',
                content: 'a `code` b',
                cursor: { line: 0, ch: 0 },
                keys: 'eee',
            },
        ],
    },
    {
        name: 'normal-search',
        cases: [
            {
                name: 'f should find char to the right',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'fw',
            },
            {
                name: 'F should find char to the left',
                content: 'hello world',
                cursor: { line: 0, ch: 10 },
                keys: 'Fo',
            },
            {
                name: 't should move till before char',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'tw',
            },
            {
                name: 'T should move till after char',
                content: 'hello world',
                cursor: { line: 0, ch: 10 },
                keys: 'To',
            },
            {
                name: '2f should find second occurrence',
                content: 'abacada',
                cursor: { line: 0, ch: 0 },
                keys: '2fa',
            },
            {
                name: 'f should not move when char not found',
                content: 'abcdef',
                cursor: { line: 0, ch: 0 },
                keys: 'fz',
            },
            {
                name: 'f should not cross line boundary',
                content: 'abc\ndef',
                cursor: { line: 0, ch: 0 },
                keys: 'fe',
            },
            {
                name: 't should stop one char before target',
                content: 'abcdef',
                cursor: { line: 0, ch: 0 },
                keys: 'td',
            },
            {
                name: 'T should stop one char after target',
                content: 'abcdef',
                cursor: { line: 0, ch: 5 },
                keys: 'Tc',
            },
            {
                name: '2t should find second and stop before',
                content: 'axbxcxd',
                cursor: { line: 0, ch: 0 },
                keys: '2tx',
            },
            {
                name: 'F should not move when char not found',
                content: 'abcdef',
                cursor: { line: 0, ch: 5 },
                keys: 'Fz',
            },
            {
                name: '2F should find second backward',
                content: 'axbxcxd',
                cursor: { line: 0, ch: 6 },
                keys: '2Fx',
            },
        ],
    },
    {
        name: 'normal-marks-jumps',
        cases: [
            {
                name: '} should move to next empty line',
                content: 'line1\nline2\n\nline4\nline5',
                cursor: { line: 0, ch: 0 },
                keys: '}',
            },
            {
                name: '{ should move to previous empty line',
                content: 'line1\nline2\n\nline4\nline5',
                cursor: { line: 4, ch: 0 },
                keys: '{',
            },
            {
                name: '2} should move 2 paragraphs forward',
                content: 'a\n\nb\n\nc',
                cursor: { line: 0, ch: 0 },
                keys: '2}',
            },
            {
                name: '} at end should not move',
                content: 'a\n\nb',
                cursor: { line: 2, ch: 0 },
                keys: '}',
            },
            {
                name: '{ at start should not move',
                content: 'a\n\nb',
                cursor: { line: 0, ch: 0 },
                keys: '{',
            },
            {
                name: '2{ should move 2 paragraphs backward',
                content: 'a\n\nb\n\nc',
                cursor: { line: 4, ch: 0 },
                keys: '2{',
            },
            {
                name: '% should jump to matching paren',
                content: '(hello world)',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
            {
                name: '% should jump back from closing paren',
                content: '(hello world)',
                cursor: { line: 0, ch: 12 },
                keys: '%',
            },
            {
                name: '% should work with curly braces',
                content: '{ code }',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
            {
                name: '% should work with square brackets',
                content: '[items]',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
            {
                name: '% across lines',
                content: '(\nhello\n)',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
            {
                name: '% with nested brackets',
                content: '(a(b)c)',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
            {
                name: '% on inner bracket',
                content: '(a(b)c)',
                cursor: { line: 0, ch: 2 },
                keys: '%',
            },
            {
                name: 'N after / search should go to previous match',
                content:
                    'word\n(word)\n{word\nword.\n\nword search\n}word\nword\nword',
                cursor: { line: 5, ch: 5 },
                keys: '/word\nN',
            },
        ],
    },
    {
        name: 'operator-combos',
        cases: [
            {
                name: 'dw should delete to next word',
                content: 'one two three',
                cursor: { line: 0, ch: 0 },
                keys: 'dw',
            },
            {
                name: 'd$ should delete to end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: 'd$',
            },
            {
                name: 'd0 should delete to start of line',
                content: 'hello world',
                cursor: { line: 0, ch: 6 },
                keys: 'd0',
            },
            {
                name: 'dj should delete current and next line',
                content: 'one\ntwo\nthree',
                cursor: { line: 0, ch: 0 },
                keys: 'dj',
            },
            {
                name: 'dw on last word should not delete newline',
                content: 'hello\nworld',
                cursor: { line: 0, ch: 0 },
                keys: 'dw',
            },
            {
                name: 'dw should delete whitespace',
                content: 'one   two',
                cursor: { line: 0, ch: 3 },
                keys: 'dw',
            },
            {
                name: 'dd on last line',
                content: 'one\ntwo',
                cursor: { line: 1, ch: 0 },
                keys: 'dd',
            },
            {
                name: 'dd on only line',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'dd',
            },
            {
                name: 'd2w should delete 2 words',
                content: 'one two three four',
                cursor: { line: 0, ch: 0 },
                keys: 'd2w',
            },
            {
                name: '2dd should delete 2 lines',
                content: 'one\ntwo\nthree\nfour',
                cursor: { line: 0, ch: 0 },
                keys: '2dd',
            },
            {
                name: 'D should delete to end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: 'D',
            },
            {
                name: 'dk should delete current and previous',
                content: 'one\ntwo\nthree',
                cursor: { line: 1, ch: 0 },
                keys: 'dk',
            },
            {
                name: 'de should delete to end of word',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'de',
            },
            {
                name: 'db should delete backward',
                content: 'hello world',
                cursor: { line: 0, ch: 8 },
                keys: 'db',
            },
            {
                name: 'd$ cursor in middle',
                content: 'abcdef',
                cursor: { line: 0, ch: 2 },
                keys: 'd$',
            },
            {
                name: 'd0 at start should not delete',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'd0',
            },
            {
                name: 'dgg should delete to start',
                content: 'one\ntwo\nthree\nfour',
                cursor: { line: 2, ch: 0 },
                keys: 'dgg',
            },
            {
                name: 'dfx should delete through char',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'dfo',
            },
            {
                name: 'dtx should delete up to char',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'dto',
            },
            {
                name: 'x should delete char under cursor',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'x',
            },
            {
                name: 'X should delete char before cursor',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'X',
            },
            {
                name: '3x should delete 3 chars',
                content: 'abcde',
                cursor: { line: 0, ch: 0 },
                keys: '3x',
            },
            {
                name: 'dd should delete current line',
                content: 'line1\nline2\nline3',
                cursor: { line: 1, ch: 0 },
                keys: 'dd',
            },
            {
                name: 'dd should preserve cursor column',
                content: '  hello\n  world\n  third',
                cursor: { line: 0, ch: 4 },
                keys: 'dd',
            },
            {
                name: '2dd should preserve cursor column',
                content: '  hello\n  world\n  third\n  fourth',
                cursor: { line: 0, ch: 3 },
                keys: '2dd',
            },
            {
                name: 'dj should preserve cursor column',
                content: '  aaa\n  bbb\n  ccc',
                cursor: { line: 0, ch: 4 },
                keys: 'dj',
            },
            {
                name: 'dk should preserve cursor column',
                content: '  aaa\n  bbb\n  ccc',
                cursor: { line: 1, ch: 4 },
                keys: 'dk',
            },
            {
                name: 'dd should clamp column to shorter line',
                content: 'long line here\nhi\nthird',
                cursor: { line: 0, ch: 10 },
                keys: 'dd',
            },
            {
                name: 'J should join lines with space',
                content: 'hello\nworld',
                cursor: { line: 0, ch: 0 },
                keys: 'J',
            },
            {
                name: 'J should strip trailing whitespace before join',
                content: 'hello \n    world',
                cursor: { line: 0, ch: 0 },
                keys: 'J',
            },
            {
                name: 'J should strip leading whitespace from next line',
                content: 'hello\n    world',
                cursor: { line: 0, ch: 0 },
                keys: 'J',
            },
            {
                name: '3J should join 3 lines stripping whitespace',
                content: 'aaa \n  bbb\nccc',
                cursor: { line: 0, ch: 0 },
                keys: '3J',
            },
            {
                name: 'r should replace single char',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'rX',
            },
            {
                name: '>> should indent line',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: '>>',
            },
            {
                name: '<< should unindent line',
                content: '\thello',
                cursor: { line: 0, ch: 0 },
                keys: '<<',
            },
            {
                name: 'dw on empty line before whitespace should place cursor correctly',
                content: '\n  \nword',
                cursor: { line: 0, ch: 0 },
                keys: 'dw',
            },
            {
                name: 'd2w should delete across line boundary',
                content: ' word1\nword2',
                cursor: { line: 0, ch: 1 },
                keys: 'd2w',
            },
            {
                name: 'dge on empty lines should delete all',
                content: '\n\n',
                cursor: { line: 1, ch: 0 },
                keys: 'dge',
            },
            {
                name: 'db should delete across line boundary including whitespace',
                content: ' word1\nword2 ',
                cursor: { line: 1, ch: 0 },
                keys: 'db',
            },
            {
                name: '% should skip quoted brackets',
                content: '(a")"b)',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
        ],
    },
    {
        name: 'text-objects-builtin',
        cases: [
            {
                name: 'diw should delete inner word',
                content: 'hello world foo',
                cursor: { line: 0, ch: 8 },
                keys: 'diw',
            },
            {
                name: 'daw should delete a word with space',
                content: 'hello world foo',
                cursor: { line: 0, ch: 6 },
                keys: 'daw',
            },
            {
                name: 'diW should delete inner WORD',
                content: 'hello foo-bar baz',
                cursor: { line: 0, ch: 8 },
                keys: 'diW',
            },
            {
                name: 'daW should delete a WORD with space',
                content: 'hello foo-bar baz',
                cursor: { line: 0, ch: 6 },
                keys: 'daW',
            },
            {
                name: 'di( should delete inside parens',
                content: 'call(arg1, arg2)',
                cursor: { line: 0, ch: 8 },
                keys: 'di(',
            },
            {
                name: 'da( should delete including parens',
                content: 'call(arg1, arg2) end',
                cursor: { line: 0, ch: 8 },
                keys: 'da(',
            },
            {
                name: 'di" should delete inside quotes',
                content: 'say "hello world" end',
                cursor: { line: 0, ch: 8 },
                keys: 'di"',
            },
            {
                name: 'da" should delete including quotes',
                content: 'say "hello world" end',
                cursor: { line: 0, ch: 8 },
                keys: 'da"',
            },
            {
                name: "di' should delete inside single quotes",
                content: "say 'hello' end",
                cursor: { line: 0, ch: 6 },
                keys: "di'",
            },
            {
                name: 'di{ should delete inside braces',
                content: 'obj{ key: val }',
                cursor: { line: 0, ch: 8 },
                keys: 'di{',
            },
            {
                name: 'da{ should delete including braces',
                content: 'obj{ key: val } end',
                cursor: { line: 0, ch: 8 },
                keys: 'da{',
            },
            {
                name: 'di[ should delete inside brackets',
                content: 'arr[1, 2, 3]',
                cursor: { line: 0, ch: 6 },
                keys: 'di[',
            },
            {
                name: 'diw on whitespace',
                content: 'hello   world',
                cursor: { line: 0, ch: 6 },
                keys: 'diw',
            },
            {
                name: 'daw at end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 6 },
                keys: 'daw',
            },
            {
                name: 'di( with nested parens',
                content: '(outer (inner) more)',
                cursor: { line: 0, ch: 10 },
                keys: 'di(',
            },
            {
                name: 'di( across lines',
                content: '(\nhello\n)',
                cursor: { line: 1, ch: 0 },
                keys: 'di(',
            },
            {
                name: 'di{ with nested braces',
                content: '{ outer { inner } more }',
                cursor: { line: 0, ch: 12 },
                keys: 'di{',
            },
            {
                name: 'di[ with nested brackets',
                content: '[outer [inner] more]',
                cursor: { line: 0, ch: 10 },
                keys: 'di[',
            },
            {
                name: 'diW with mixed punctuation',
                content: 'hello foo.bar,baz end',
                cursor: { line: 0, ch: 10 },
                keys: 'diW',
            },
            {
                name: 'd2aw should delete 2 words',
                content: 'one two three four',
                cursor: { line: 0, ch: 4 },
                keys: 'd2aw',
            },
        ],
    },
    {
        name: 'normal-editing',
        cases: [
            {
                name: 'x should delete char under cursor',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'x',
            },
            {
                name: 'X should delete char before cursor',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'X',
            },
            {
                name: '3x should delete 3 chars',
                content: 'abcde',
                cursor: { line: 0, ch: 0 },
                keys: '3x',
            },
            {
                name: 'dd should delete current line',
                content: 'line1\nline2\nline3',
                cursor: { line: 1, ch: 0 },
                keys: 'dd',
            },
            {
                name: 'D should delete to end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: 'D',
            },
            {
                name: '2dd should delete 2 lines',
                content: 'one\ntwo\nthree\nfour',
                cursor: { line: 1, ch: 0 },
                keys: '2dd',
            },
            {
                name: 'dw should delete word',
                content: 'hello world foo',
                cursor: { line: 0, ch: 0 },
                keys: 'dw',
            },
            {
                name: 'cc should change entire line',
                content: 'old text\nkeep this',
                cursor: { line: 0, ch: 0 },
                keys: 'ccnew\x1b',
            },
            {
                name: 'C should change to end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: 'C!\x1b',
            },
            {
                name: 'cw should change word',
                content: 'old new end',
                cursor: { line: 0, ch: 0 },
                keys: 'cwrep\x1b',
            },
            {
                name: 's should substitute char',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'sX\x1b',
            },
            {
                name: 'S should substitute entire line',
                content: 'old line\nkeep',
                cursor: { line: 0, ch: 3 },
                keys: 'Snew\x1b',
            },
            {
                name: 'r should replace single char',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'rX',
            },
            {
                name: 'R should enter replace mode',
                content: 'abcde',
                cursor: { line: 0, ch: 0 },
                keys: 'RXY\x1b',
            },
            {
                name: 'J should join lines with space',
                content: 'hello\nworld',
                cursor: { line: 0, ch: 0 },
                keys: 'J',
            },
            {
                name: '~ should toggle case',
                content: 'Hello',
                cursor: { line: 0, ch: 0 },
                keys: '~',
            },
            {
                name: 'u should undo last change',
                content: 'original',
                cursor: { line: 0, ch: 0 },
                keys: 'ddu',
            },
            {
                name: '. should repeat dd',
                content: 'aaa\nbbb\nccc',
                cursor: { line: 0, ch: 0 },
                keys: 'dd.',
            },
            {
                name: '. should repeat dw',
                content: 'one two three four',
                cursor: { line: 0, ch: 0 },
                keys: 'dw.',
            },
            {
                name: '3. should repeat with count',
                content: 'abcde',
                cursor: { line: 0, ch: 0 },
                keys: 'x3.',
            },
            {
                name: '. should repeat cw with text',
                content: 'old old old',
                cursor: { line: 0, ch: 0 },
                keys: 'cwnew \x1bw.',
            },
        ],
    },
    {
        name: 'normal-yank-put',
        cases: [
            {
                name: 'yy then p should paste line below',
                content: 'hello world\nsecond line',
                cursor: { line: 0, ch: 0 },
                keys: 'yyp',
            },
            {
                name: 'dd then p should paste deleted line below',
                content: 'first\nsecond\nthird',
                cursor: { line: 0, ch: 0 },
                keys: 'ddp',
            },
            {
                name: 'yw then p should paste word',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'yw$p',
            },
            {
                name: 'P should paste before cursor',
                content: 'world',
                cursor: { line: 0, ch: 0 },
                keys: 'yw0P',
            },
            {
                name: '"ayy then "ap should paste from register a',
                content: 'alpha line\nbeta line',
                cursor: { line: 0, ch: 0 },
                keys: '"ayyG"ap',
            },
            {
                name: 'y$ should yank to end without newline',
                content: 'hello world\nsecond',
                cursor: { line: 0, ch: 6 },
                keys: 'y$jp',
            },
            {
                name: '2yy then p should paste 2 lines',
                content: 'one\ntwo\nthree',
                cursor: { line: 0, ch: 0 },
                keys: '2yyGp',
            },
            {
                name: '"Ayy should append to register a',
                content: 'first\nsecond\nthird',
                cursor: { line: 0, ch: 0 },
                keys: '"ayyj"AyyG"ap',
            },
            {
                name: 'dd then "0p should paste last yank not delete',
                content: 'alpha\nbeta\ngamma',
                cursor: { line: 0, ch: 0 },
                keys: 'yyjdd"0p',
            },
            {
                name: '"ayy "byy should store independently',
                content: 'AAA\nBBB\nCCC',
                cursor: { line: 0, ch: 0 },
                keys: '"ayyj"byyG"ap"bp',
            },
        ],
    },
    {
        name: 'normal-insert-entry',
        cases: [
            {
                name: 'i should insert text before cursor',
                content: 'hello',
                cursor: { line: 0, ch: 2 },
                keys: 'iX\x1b',
            },
            {
                name: 'a should insert text after cursor',
                content: 'hello',
                cursor: { line: 0, ch: 2 },
                keys: 'aX\x1b',
            },
            {
                name: 'I should insert at first non-blank',
                content: '  hello',
                cursor: { line: 0, ch: 4 },
                keys: 'IX\x1b',
            },
            {
                name: 'A should append at end of line',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'A!\x1b',
            },
            {
                name: 'o should open line below',
                content: 'line1\nline2',
                cursor: { line: 0, ch: 0 },
                keys: 'onew\x1b',
            },
            {
                name: 'O should open line above',
                content: 'line1\nline2',
                cursor: { line: 1, ch: 0 },
                keys: 'Onew\x1b',
            },
        ],
    },
    {
        name: 'visual-mode',
        cases: [
            {
                name: 'v + e + d should delete selection',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ved',
            },
            {
                name: 'V + d should delete entire line',
                content: 'line1\nline2\nline3',
                cursor: { line: 1, ch: 0 },
                keys: 'Vd',
            },
            {
                name: 'V + j + d should delete multiple lines',
                content: 'one\ntwo\nthree\nfour',
                cursor: { line: 1, ch: 0 },
                keys: 'Vjd',
            },
            {
                name: 'v + iw + d should delete word',
                content: 'hello world foo',
                cursor: { line: 0, ch: 7 },
                keys: 'viwd',
            },
            {
                name: 'v + 3l + d should delete 4 chars',
                content: 'abcdefgh',
                cursor: { line: 0, ch: 0 },
                keys: 'v3ld',
            },
            {
                name: 'V + > should indent line',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'V>',
            },
            {
                name: 'V + J should join selected lines',
                content: 'line one\nline two\nline three',
                cursor: { line: 0, ch: 0 },
                keys: 'VjJ',
            },
            {
                name: 'v$ cursor position at end of line',
                content: 'hello world\nsecond line',
                cursor: { line: 0, ch: 0 },
                keys: 'v$',
            },
            {
                name: 'v$ then Escape should leave cursor at EOL',
                content: 'hello world\nsecond line',
                cursor: { line: 0, ch: 0 },
                keys: 'v$\x1b',
            },
            {
                name: 'vl to end of short line',
                content: 'abc\ndefgh',
                cursor: { line: 0, ch: 0 },
                keys: 'vlll',
            },
            {
                name: 'V cursor position on single line',
                content: 'hello world\nsecond line',
                cursor: { line: 0, ch: 0 },
                keys: 'V',
            },
            {
                name: 'V on empty line',
                content: 'first\n\nthird',
                cursor: { line: 1, ch: 0 },
                keys: 'V',
            },
            {
                name: 'v$ on middle of line',
                content: 'abcdef\nghijkl',
                cursor: { line: 0, ch: 2 },
                keys: 'v$',
            },
            {
                name: 'v$ then y should yank to end of line',
                content: 'hello world\nsecond',
                cursor: { line: 0, ch: 5 },
                keys: 'v$y',
            },
            {
                name: 'V then Escape cursor position',
                content: 'hello world\nsecond line',
                cursor: { line: 0, ch: 5 },
                keys: 'V\x1b',
            },
            {
                name: 'Vj cursor position',
                content: 'first\nsecond\nthird',
                cursor: { line: 0, ch: 0 },
                keys: 'Vj',
            },
            {
                name: 'v$ on last line without trailing newline',
                content: 'only line',
                cursor: { line: 0, ch: 0 },
                keys: 'v$',
            },
            {
                name: 'V + j + y cursor position after yank',
                content: 'first\nsecond\nthird\nfourth',
                cursor: { line: 0, ch: 0 },
                keys: 'Vjy',
            },
            {
                name: 'V + 2j + d should delete three lines',
                content: 'one\ntwo\nthree\nfour\nfive',
                cursor: { line: 1, ch: 0 },
                keys: 'V2jd',
            },
            {
                name: 'V + k cursor position moving up',
                content: 'first\nsecond\nthird',
                cursor: { line: 2, ch: 0 },
                keys: 'Vk',
            },
            {
                name: 'V + j + k cursor position back to start',
                content: 'first\nsecond\nthird',
                cursor: { line: 1, ch: 0 },
                keys: 'Vjk',
            },
            {
                name: 'v then V should switch to linewise delete',
                content: 'hello world\nsecond line\nthird',
                cursor: { line: 0, ch: 3 },
                keys: 'vllVd',
            },
            {
                name: 'V then v should switch to charwise',
                content: 'hello world\nsecond line',
                cursor: { line: 0, ch: 0 },
                keys: 'Vveld',
            },
            {
                name: 'V from mid-column + j + d should delete two lines',
                content: '- alpha\n- [ ] beta\n- gamma',
                cursor: { line: 0, ch: 2 },
                keys: 'Vjd',
            },
            {
                name: 'V from mid-column + 2j + y cursor at col 0',
                content: '- one\n- two\n- three\n- four',
                cursor: { line: 0, ch: 3 },
                keys: 'V2jy',
            },
        ],
    },
    {
        name: 'g-commands',
        cases: [
            {
                name: 'gj should move one display line down',
                content: 'short\nline two',
                cursor: { line: 0, ch: 0 },
                keys: 'gj',
            },
            {
                name: 'gk should move one display line up',
                content: 'line one\nshort',
                cursor: { line: 1, ch: 0 },
                keys: 'gk',
            },
            {
                name: 'g0 should move to start of display line',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: 'g0',
            },
            {
                name: 'g$ should move to end of display line',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'g$',
            },
            {
                name: 'guu should lowercase entire line',
                content: 'HELLO WORLD',
                cursor: { line: 0, ch: 0 },
                keys: 'guu',
            },
            {
                name: 'gUU should uppercase entire line',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'gUU',
            },
            {
                name: 'guw should lowercase word',
                content: 'HELLO world',
                cursor: { line: 0, ch: 0 },
                keys: 'guw',
            },
            {
                name: 'gUw should uppercase word',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'gUw',
            },
            {
                name: 'g~~ should toggle case of line',
                content: 'Hello World',
                cursor: { line: 0, ch: 0 },
                keys: 'g~~',
            },
            {
                name: 'gI should insert at column 0',
                content: '  hello',
                cursor: { line: 0, ch: 4 },
                keys: 'gIX\x1b',
            },
            {
                name: 'gJ should join lines without space',
                content: 'hello\nworld',
                cursor: { line: 0, ch: 0 },
                keys: 'gJ',
            },
            {
                name: 'ga should not move cursor',
                content: 'Hello',
                cursor: { line: 0, ch: 0 },
                keys: 'ga',
            },
            {
                name: 'gqq should reformat current line',
                content: 'short line here',
                cursor: { line: 0, ch: 0 },
                keys: 'gqq',
            },
            {
                name: 'Vgq should reformat selected line',
                content: 'short line here',
                cursor: { line: 0, ch: 0 },
                keys: 'Vgq',
            },
            {
                name: 'gqj should reformat current and next line',
                content: 'short line one\nshort line two',
                cursor: { line: 0, ch: 0 },
                keys: 'gqj',
            },
        ],
    },
    {
        name: 'bracket-commands',
        cases: [
            {
                name: '[( should jump to previous unmatched (',
                content: '(hello (world) end)',
                cursor: { line: 0, ch: 10 },
                keys: '[(',
            },
            {
                name: ']) should jump to next unmatched )',
                content: '(hello (world) end)',
                cursor: { line: 0, ch: 10 },
                keys: '])',
            },
            {
                name: '[{ should jump to previous unmatched {',
                content: '{ outer { inner } end }',
                cursor: { line: 0, ch: 12 },
                keys: '[{',
            },
            {
                name: ']} should jump to next unmatched }',
                content: '{ outer { inner } end }',
                cursor: { line: 0, ch: 12 },
                keys: ']}',
            },
        ],
    },
    {
        name: 'insert-mode',
        cases: [
            {
                name: 'Escape from insert should allow x to delete',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'i\x1bx',
            },
            {
                name: 'Ctrl-W should delete word in insert',
                content: '',
                cursor: { line: 0, ch: 0 },
                keys: 'ihello world\x17\x1b',
            },
            {
                name: 'Ctrl-U should delete to start in insert',
                content: '',
                cursor: { line: 0, ch: 0 },
                keys: 'ihello\x15\x1b',
            },
            {
                name: 'Ctrl-O should execute one normal command',
                content: 'hello\nworld',
                cursor: { line: 1, ch: 0 },
                keys: 'i\x0fk\x1b',
            },
        ],
    },
    {
        name: 'normal-scroll',
        cases: [
            {
                name: 'Ctrl-A should increment number',
                content: 'count: 5',
                cursor: { line: 0, ch: 7 },
                keys: '\x01',
            },
            {
                name: 'Ctrl-X should decrement number',
                content: 'count: 5',
                cursor: { line: 0, ch: 7 },
                keys: '\x18',
            },
        ],
    },
    {
        name: 'ex-commands-builtin',
        cases: [
            {
                name: ':s/old/new/ should replace first on line',
                content: 'old old old',
                cursor: { line: 0, ch: 0 },
                keys: ':s/old/new/\n',
            },
            {
                name: ':s/old/new/g should replace all on line',
                content: 'old old old',
                cursor: { line: 0, ch: 0 },
                keys: ':s/old/new/g\n',
            },
            {
                name: ':sort should sort lines',
                content: 'cherry\napple\nbanana',
                cursor: { line: 0, ch: 0 },
                keys: ':sort\n',
            },
            {
                name: ':d should delete current line',
                content: 'one\ntwo\nthree',
                cursor: { line: 1, ch: 0 },
                keys: ':d\n',
            },
            {
                name: ':%s should replace across all lines',
                content: 'old\nold\nold',
                cursor: { line: 0, ch: 0 },
                keys: ':%s/old/new/g\n',
            },
            {
                name: ':2,3s should replace in range',
                content: 'keep\nchange\nchange\nkeep',
                cursor: { line: 0, ch: 0 },
                keys: ':2,3s/change/done/g\n',
            },
        ],
    },
    {
        name: 'ex-commands-expanded',
        cases: [
            {
                name: ':yank should not error',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: ':yank\n',
            },
            {
                name: ':join should join lines',
                content: 'one\ntwo\nthree',
                cursor: { line: 0, ch: 0 },
                keys: ':join\n',
            },
            {
                name: ':nohlsearch should not error',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: ':nohlsearch\n',
            },
            {
                name: ':undo should undo',
                content: 'original',
                cursor: { line: 0, ch: 0 },
                keys: 'dd\n:undo\n',
            },
            {
                name: ':redo should redo',
                content: 'original',
                cursor: { line: 0, ch: 0 },
                keys: 'ddu\n:redo\n',
            },
            {
                name: ':global should execute on matching lines',
                content: 'keep\nremove\nkeep\nremove',
                cursor: { line: 0, ch: 0 },
                keys: ':g/remove/d\n',
            },
        ],
    },
    {
        name: 'visual-block',
        cases: [
            {
                name: 'CTRL-V block insert at left column',
                content: 'abc\ndef\nghi',
                cursor: { line: 0, ch: 0 },
                keys: '\x16jjIX\x1b',
            },
            {
                name: 'CTRL-V block insert at right column',
                content: 'abc\ndef\nghi',
                cursor: { line: 0, ch: 0 },
                keys: '\x16jjAX\x1b',
            },
            {
                name: 'CTRL-V block change',
                content: 'abcd\nefgh\nijkl',
                cursor: { line: 0, ch: 1 },
                keys: '\x16jjlcXY\x1b',
            },
            {
                name: 'CTRL-V block change to EOL',
                content: 'abcdef\nghijkl\nmnopqr',
                cursor: { line: 0, ch: 2 },
                keys: '\x16jjlCXY\x1b',
            },
            {
                name: 'CTRL-V block delete',
                content: 'abc\ndef\nghi',
                cursor: { line: 0, ch: 0 },
                keys: '\x16jjx',
            },
            {
                name: 'CTRL-V block case toggle',
                content: 'abcDEF\nghiJKL\nmnoPQR',
                cursor: { line: 0, ch: 0 },
                keys: '\x16jjll~',
            },
            {
                name: 'CTRL-V block replace',
                content: 'abcd\nefgh\nijkl',
                cursor: { line: 0, ch: 1 },
                keys: '\x16jjllrX',
            },
            {
                name: 'CTRL-V block insert pads short lines',
                content: 'abcdefgh\nab\nabcde',
                cursor: { line: 0, ch: 5 },
                keys: '\x16jjIX\x1b',
            },
            {
                name: 'CTRL-V block yank then paste',
                content: 'abc\ndef\nghi\n---',
                cursor: { line: 0, ch: 0 },
                keys: '\x16jjlyGp',
            },
            {
                name: 'CTRL-V zero-width block C to EOL',
                content: 'abcdef\nghijkl\nmnopqr',
                cursor: { line: 0, ch: 2 },
                keys: '\x16jjCXY\x1b',
            },
            {
                name: 'CTRL-V zero-width block I',
                content: 'abcdef\nghijkl\nmnopqr',
                cursor: { line: 0, ch: 2 },
                keys: '\x16jjIX\x1b',
            },
            {
                name: 'CTRL-V block A cursor at left edge',
                content: 'abc\ndef\nghi',
                cursor: { line: 0, ch: 1 },
                keys: '\x16jjAX\x1b',
            },
            {
                name: 'CTRL-V block I upward selection',
                content: 'abc\ndef\nghi',
                cursor: { line: 2, ch: 0 },
                keys: '\x16kkIX\x1b',
            },
            {
                name: 'CTRL-V $ Escape cursor position',
                content: 'abcdef\ngh\nijklmnop',
                cursor: { line: 0, ch: 1 },
                keys: '\x16jj$\x1b',
            },
            {
                name: 'CTRL-V $ delete to EOL',
                content: 'abc\nde\nfghij',
                cursor: { line: 0, ch: 1 },
                keys: '\x16jj$d',
            },
        ],
    },
    {
        name: 'upstream-gaps',
        cases: [
            {
                name: 'dip inside empty lines deletes empty paragraph block',
                content: 'a\na\n\n\n\nb\nc\n\n\n\n\n\n\nd\n\ne\nf',
                cursor: { line: 10, ch: 0 },
                keys: 'dip',
            },
            {
                name: 'CTRL-V backward block A appends at right edge',
                content: '01234 line 1\n56789 line 2\nabcdefg line 3\nline 4',
                cursor: { line: 0, ch: 3 },
                keys: '\x162j2hAhello\x1b',
            },
            {
                name: 'CTRL-V block A pads short lines',
                content: 'test\nme\nplease',
                cursor: { line: 0, ch: 1 },
                keys: '\x162jllAhello\x1b',
            },
            {
                name: 'visual r Space across line boundary',
                content: 'wordet\nanother',
                cursor: { line: 0, ch: 1 },
                keys: '3rulvjhr ',
            },
            {
                name: 'CTRL-V to v switch then delete',
                content: '12345\n67891\nabcde',
                cursor: { line: 1, ch: 1 },
                keys: '\x16jlvd',
            },
            {
                name: 'CTRL-V to V switch then delete',
                content: '12345\n67891\nabcde',
                cursor: { line: 1, ch: 1 },
                keys: '\x16jlVd',
            },
            {
                name: 'macro insert repeat with dot',
                content: '',
                cursor: { line: 0, ch: 0 },
                keys: 'qa$alarry.\x1bacurly.\x1bqamoe.\x1b@a.',
            },
        ],
    },
    {
        name: 'surround',
        nvimSetup: [
            'set runtimepath+=/tmp/opencode/nvim-surround',
            'runtime plugin/nvim-surround.lua',
            'lua require("nvim-surround").setup()',
        ],
        cases: [
            {
                name: 'ds" removes double quotes',
                content: '"hello world"',
                cursor: { line: 0, ch: 5 },
                keys: 'ds"',
            },
            {
                name: "ds' removes single quotes",
                content: "'hello world'",
                cursor: { line: 0, ch: 5 },
                keys: "ds'",
            },
            {
                name: 'ds( removes parens with spaces',
                content: '( hello world )',
                cursor: { line: 0, ch: 5 },
                keys: 'ds(',
            },
            {
                name: 'ds) removes parens without spaces',
                content: '(hello world)',
                cursor: { line: 0, ch: 5 },
                keys: 'ds)',
            },
            {
                name: 'ds[ removes brackets with spaces',
                content: '[ hello world ]',
                cursor: { line: 0, ch: 5 },
                keys: 'ds[',
            },
            {
                name: 'ds] removes brackets without spaces',
                content: '[hello world]',
                cursor: { line: 0, ch: 5 },
                keys: 'ds]',
            },
            {
                name: 'ds{ removes braces with spaces',
                content: '{ hello world }',
                cursor: { line: 0, ch: 5 },
                keys: 'ds{',
            },
            {
                name: 'ds} removes braces without spaces',
                content: '{hello world}',
                cursor: { line: 0, ch: 5 },
                keys: 'ds}',
            },
            {
                name: 'ds` removes backticks',
                content: '`hello world`',
                cursor: { line: 0, ch: 5 },
                keys: 'ds`',
            },
            {
                name: 'dsb removes parens (alias)',
                content: '(hello)',
                cursor: { line: 0, ch: 3 },
                keys: 'dsb',
            },
            {
                name: 'dsB removes braces (alias)',
                content: '{hello}',
                cursor: { line: 0, ch: 3 },
                keys: 'dsB',
            },
            {
                name: 'cs"\' changes double to single quotes',
                content: '"hello world"',
                cursor: { line: 0, ch: 5 },
                keys: 'cs"\'',
            },
            {
                name: 'cs({ changes parens to brackets',
                content: '(hello)',
                cursor: { line: 0, ch: 3 },
                keys: 'cs({',
            },
            {
                name: 'cs)[ changes parens to brackets with spaces',
                content: '(hello)',
                cursor: { line: 0, ch: 3 },
                keys: 'cs)[',
            },
            {
                name: 'cs"( changes quotes to parens with spaces',
                content: '"hello"',
                cursor: { line: 0, ch: 3 },
                keys: 'cs"(',
            },
            {
                name: 'cs") changes quotes to parens without spaces',
                content: '"hello"',
                cursor: { line: 0, ch: 3 },
                keys: 'cs")',
            },
            {
                name: 'ysiw" surrounds word with quotes',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ysiw"',
            },
            {
                name: 'ysiw) surrounds word with parens',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ysiw)',
            },
            {
                name: 'ysiw( surrounds word with parens and spaces',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ysiw(',
            },
            {
                name: 'yss" surrounds entire line with quotes',
                content: 'hello world',
                cursor: { line: 0, ch: 3 },
                keys: 'yss"',
            },
            {
                name: 'yss) surrounds entire line with parens',
                content: 'hello world',
                cursor: { line: 0, ch: 3 },
                keys: 'yss)',
            },
            {
                name: 'visual S" surrounds selection with quotes',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'viwS"',
            },
            {
                name: 'visual S) surrounds selection with parens',
                content: 'hello world',
                cursor: { line: 0, ch: 6 },
                keys: 'viwS)',
            },
            {
                name: 'ds" cursor on opening quote',
                content: '"hello"',
                cursor: { line: 0, ch: 0 },
                keys: 'ds"',
            },
            {
                name: 'ds" cursor on closing quote',
                content: '"hello"',
                cursor: { line: 0, ch: 6 },
                keys: 'ds"',
            },
            {
                name: 'ds( nested parens removes outer',
                content: '((inner))',
                cursor: { line: 0, ch: 0 },
                keys: 'ds(',
            },
            {
                name: 'ds) nested parens removes inner',
                content: '((inner))',
                cursor: { line: 0, ch: 2 },
                keys: 'ds)',
            },
            {
                name: 'yss preserves leading indent',
                content: '    hello world',
                cursor: { line: 0, ch: 6 },
                keys: 'yss"',
            },
            {
                name: 'ds( multiline parens',
                content: '(\nhello\nworld\n)',
                cursor: { line: 1, ch: 0 },
                keys: 'ds(',
            },
            {
                name: '2dsb removes 2nd-level parens',
                content: '((foo) bar (baz))',
                cursor: { line: 0, ch: 8 },
                keys: '2dsb',
            },
            {
                name: '3dsb removes 3 levels of parens',
                content: '(((foo)))',
                cursor: { line: 0, ch: 4 },
                keys: '3dsb',
            },
            {
                name: '2csbB changes 2nd-level parens to braces',
                content: '((foo) bar (baz))',
                cursor: { line: 0, ch: 8 },
                keys: '2csbB',
            },
            {
                name: '3csbr changes 3 levels to brackets',
                content: '(((foo)))',
                cursor: { line: 0, ch: 4 },
                keys: '3csbr',
            },
            {
                name: '2ysiw* adds double-star bold',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: '2ysiw*',
            },
            {
                name: '2yss* double-star entire line',
                content: 'hello world',
                cursor: { line: 0, ch: 3 },
                keys: '2yss*',
            },
            {
                name: 'ysiwb then . dot-repeat adds layers',
                content: 'test',
                cursor: { line: 0, ch: 0 },
                keys: 'ysiwb..',
            },
            {
                name: 'dsb then . dot-repeat removes layers',
                content: '(((test)))',
                cursor: { line: 0, ch: 0 },
                keys: 'dsb..',
            },
            {
                name: 'csba then . dot-repeat changes layers',
                content: '(((test)))',
                cursor: { line: 0, ch: 0 },
                keys: 'csba..',
            },
            {
                name: 'dst deletes surrounding tag',
                content: '<div>hello</div>',
                cursor: { line: 0, ch: 5 },
                keys: 'dst',
            },
            {
                name: 'cst<p> changes tag to p',
                content: '<em>hello</em>',
                cursor: { line: 0, ch: 5 },
                keys: 'cst<p>\n',
            },
            {
                name: 'ysiwtdiv wraps word with div tag',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ysiwt div\n',
            },
            {
                name: 'cst" changes tag to quotes',
                content: '<em>hello</em>',
                cursor: { line: 0, ch: 5 },
                keys: 'cst"',
            },
            {
                name: 'dst on nested removes inner tag',
                content: '<div><em>hello</em></div>',
                cursor: { line: 0, ch: 11 },
                keys: 'dst',
            },
            {
                name: 'dsf deletes surrounding function call',
                content: 'some_func(some_args)',
                cursor: { line: 0, ch: 0 },
                keys: 'dsf',
            },
            {
                name: 'dsf on nested removes outer',
                content: 'nested(functions(here))',
                cursor: { line: 0, ch: 0 },
                keys: 'dsf',
            },
            {
                name: 'dsf on nested removes inner',
                content: 'nested(functions(here))',
                cursor: { line: 0, ch: 7 },
                keys: 'dsf',
            },
            {
                name: 'ysa"b adds parens around quoted text',
                content: '"hello"',
                cursor: { line: 0, ch: 3 },
                keys: 'ysa"b',
            },
            {
                name: 'dsb on empty parens',
                content: '()',
                cursor: { line: 0, ch: 0 },
                keys: 'dsb',
            },
            {
                name: 'dsB on empty multiline braces',
                content: '{\n\n}',
                cursor: { line: 0, ch: 0 },
                keys: 'dsB',
            },
            {
                name: 'csba changes parens to angle brackets',
                content: '(hello)',
                cursor: { line: 0, ch: 3 },
                keys: 'csba',
            },
            {
                name: 'csBr changes multiline braces to brackets',
                content: '{\n\n}',
                cursor: { line: 0, ch: 0 },
                keys: 'csBr',
            },
            {
                name: 'ysiw} closing brace no space',
                content: 'sample_text',
                cursor: { line: 0, ch: 0 },
                keys: 'ysiw}',
            },
            {
                name: 'ysiw{ opening brace with space',
                content: 'sample_text',
                cursor: { line: 0, ch: 0 },
                keys: 'ysiw{',
            },
            {
                name: 'ds{ strips spaces from braces',
                content: '({ sample_text })',
                cursor: { line: 0, ch: 2 },
                keys: 'ds{',
            },
            {
                name: 'ds} preserves spaces from braces',
                content: '({ sample_text })',
                cursor: { line: 0, ch: 2 },
                keys: 'ds}',
            },
            {
                name: 'yssb surrounds line with parens via alias',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'yssb',
            },
            {
                name: 'ys$ surrounds to end of line',
                content: 'string x = some text',
                cursor: { line: 0, ch: 11 },
                keys: 'ys$"',
            },
            {
                name: 'ysjb surrounds current and next line',
                content: 'line one\nline two\nline three',
                cursor: { line: 0, ch: 0 },
                keys: 'ysjb',
            },
            {
                name: 'ys2jB surrounds 3 lines with braces',
                content: 'first\nsecond\nthird\nfourth\nfifth',
                cursor: { line: 1, ch: 0 },
                keys: 'ys2jB',
            },
            {
                name: 'ySS] surrounds line on new lines',
                content: 'current line',
                cursor: { line: 0, ch: 6 },
                keys: 'ySSr',
            },
            {
                name: 'VSB linewise visual surround with braces',
                content: 'current line',
                cursor: { line: 0, ch: 0 },
                keys: 'VSB',
            },
            {
                name: 'dsb on multiline function',
                content: 'local func = function()\n    local x = 1\nend',
                cursor: { line: 0, ch: 21 },
                keys: 'dsb',
            },
            {
                name: 'visual block $ S} surrounds ragged lines',
                content: 'some more text\nsome lines\nhello world',
                cursor: { line: 0, ch: 0 },
                keys: '\x16jj$S}',
            },
            {
                name: 'ds on Windows line endings',
                content: '(hello world)',
                cursor: { line: 0, ch: 0 },
                keys: 'dsb',
            },
            {
                name: 'ysiw] then ysa]B wraps layer',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ysiw]ysa]B',
            },
            {
                name: 'cs)B changes parens to braces',
                content: '(hello)',
                cursor: { line: 0, ch: 3 },
                keys: 'cs)B',
            },
            {
                name: 'csbB then ysaBb chain',
                content: '(hello)',
                cursor: { line: 0, ch: 3 },
                keys: 'csbBysaBb',
            },
            {
                name: 'ysiw> surrounds with angle no space',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ysiw>',
            },
            {
                name: 'ysiw< surrounds with angle with space',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ysiw<\n',
            },
            {
                name: 'ds> removes angle brackets',
                content: '<hello>',
                cursor: { line: 0, ch: 3 },
                keys: 'ds>',
            },
            {
                name: 'ds< removes angle brackets with spaces',
                content: '< hello >',
                cursor: { line: 0, ch: 4 },
                keys: 'ds<',
            },
            {
                name: 'yss| surrounds with pipe',
                content: 'sample text',
                cursor: { line: 0, ch: 0 },
                keys: 'yss|',
            },
            {
                name: 'cs|^ changes pipe to caret',
                content: '|sample text|',
                cursor: { line: 0, ch: 5 },
                keys: 'cs|^',
            },
            {
                name: 'ds^ removes carets',
                content: '^sample text^',
                cursor: { line: 0, ch: 5 },
                keys: 'ds^',
            },
        ],
    },
    {
        name: 'dot-repeat',
        cases: [
            {
                name: '2dw then . repeats',
                content: '1 2 3 4 5 6',
                cursor: { line: 0, ch: 0 },
                keys: '2dw.',
            },
            {
                name: '2dw then 3. repeats 3x',
                content: '1 2 3 4 5 6',
                cursor: { line: 0, ch: 0 },
                keys: '2dw3.',
            },
            {
                name: 'dd then . repeats',
                content: 'one\ntwo\nthree\nfour',
                cursor: { line: 0, ch: 0 },
                keys: 'dd.',
            },
            {
                name: '3i types text 3x then . repeats',
                content: '',
                cursor: { line: 0, ch: 0 },
                keys: '3itest\x1b.',
            },
            {
                name: '3o opens 3 lines with text',
                content: '',
                cursor: { line: 0, ch: 0 },
                keys: '3otest\x1b',
            },
            {
                name: 'cw then . repeats on next word',
                content: 'word1 word2 word3',
                cursor: { line: 0, ch: 0 },
                keys: 'cwtest\x1bw.',
            },
            {
                name: 'R then . repeats on next line',
                content: 'hello\nworld',
                cursor: { line: 0, ch: 0 },
                keys: 'Rab\x1bj0.',
            },
            {
                name: '2dl deletes 2 chars',
                content: ' word1 ',
                cursor: { line: 0, ch: 0 },
                keys: '2dl',
            },
            {
                name: 'd2w deletes 2 words across lines',
                content: ' word1\nword2',
                cursor: { line: 0, ch: 1 },
                keys: 'd2w',
            },
            {
                name: 'g~2w toggles case of 2 words',
                content: ' word1\nWORD2',
                cursor: { line: 0, ch: 1 },
                keys: 'g~2w',
            },
            {
                name: '3J joins 3 lines',
                content: 'word1\n word2\n word3\n word4',
                cursor: { line: 0, ch: 4 },
                keys: '3J',
            },
            {
                name: '3I inserts text 3 times at bol',
                content: 'blah',
                cursor: { line: 0, ch: 1 },
                keys: '3Itest\x1b',
            },
            {
                name: 'V > then . indents again',
                content: '1\n2\n3\n4',
                cursor: { line: 0, ch: 0 },
                keys: 'Vj>jj.',
            },
            {
                name: '. after dd with count',
                content: '1\n2\n3\n4\n5\n6',
                cursor: { line: 0, ch: 0 },
                keys: '2dd.',
            },
            {
                name: '. after visual block ~ toggles case',
                content: 'Hello\nWorld\nAbcdE',
                cursor: { line: 0, ch: 0 },
                keys: '\x16jjl~ll.',
            },
            {
                name: '. after o inserts line below',
                content: '',
                cursor: { line: 0, ch: 0 },
                keys: 'oz\x1b.',
            },
            {
                name: 'replace dot repeat R ab then .',
                content: 'hello\nhello',
                cursor: { line: 0, ch: 0 },
                keys: 'Rab\x1bj0.',
            },
        ],
    },
    {
        name: 'select-mode-extended',
        cases: [
            {
                name: 'gh then type replaces selection',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'ghllx\x1b',
            },
            {
                name: 'gH linewise then type replaces',
                content: 'first\nsecond\nthird',
                cursor: { line: 1, ch: 0 },
                keys: 'gHjx\x1b',
            },
            {
                name: 'gh then Esc exits to normal',
                content: 'hello',
                cursor: { line: 0, ch: 2 },
                keys: 'ghl\x1b',
            },
            {
                name: 'v then Ctrl-G toggles to select then type',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'vll\x07x\x1b',
            },
            {
                name: 'gh BS deletes selection',
                content: 'hello',
                cursor: { line: 0, ch: 1 },
                keys: 'ghll\x08',
            },
            {
                name: 'Ctrl-G in select toggles back to visual',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ghll\x07d',
            },
        ],
    },
    {
        name: 'ex-sort',
        cases: [
            {
                name: ':sort alphabetically',
                content: 'b\na\nd\nc',
                cursor: { line: 0, ch: 0 },
                keys: ':sort\n',
            },
            {
                name: ':sort! reverse',
                content: 'a\nb\nc\nd',
                cursor: { line: 0, ch: 0 },
                keys: ':sort!\n',
            },
            {
                name: ':sort i case-insensitive',
                content: 'B\na\nD\nc',
                cursor: { line: 0, ch: 0 },
                keys: ':sort i\n',
            },
            {
                name: ':sort u unique',
                content: 'a\nb\na\nc\nb',
                cursor: { line: 0, ch: 0 },
                keys: ':sort u\n',
            },
            {
                name: ':sort n numeric',
                content: 'b10\na2\nc1\na20',
                cursor: { line: 0, ch: 0 },
                keys: ':sort n\n',
            },
            {
                name: ':2,3sort range',
                content: 'c\nb\na\nd',
                cursor: { line: 0, ch: 0 },
                keys: ':2,3sort\n',
            },
        ],
    },
    {
        name: 'ex-global',
        cases: [
            {
                name: ':g/pattern/d deletes matching lines',
                content: 'keep\ndelete_me\nkeep\ndelete_me\nkeep',
                cursor: { line: 0, ch: 0 },
                keys: ':g/delete/d\n',
            },
            {
                name: ':v/pattern/d deletes non-matching lines',
                content: 'keep\nremove\nkeep\nremove\nkeep',
                cursor: { line: 0, ch: 0 },
                keys: ':v/keep/d\n',
            },
            {
                name: ':g/a/s/a/x/ substitutes on matching lines',
                content: 'abc\ndef\nabc',
                cursor: { line: 0, ch: 0 },
                keys: ':g/a/s/a/x/\n',
            },
        ],
    },
    {
        name: 'marks',
        cases: [
            {
                name: "ma then 'a should jump to marked line",
                content: 'line1\nline2\nline3\nline4\nline5',
                cursor: { line: 2, ch: 3 },
                keys: "magg'a",
            },
            {
                name: '`a should jump to exact mark position',
                content: 'line1\nline2\nline3\nline4\nline5',
                cursor: { line: 3, ch: 2 },
                keys: 'mbgg`b',
            },
            {
                name: "'. should jump to line of last edit",
                content: 'line1\nline2\nline3',
                cursor: { line: 2, ch: 0 },
                keys: "xgg'.",
            },
            {
                name: "'' should jump to line before last jump",
                content: 'line1\nline2\nline3\nline4\nline5',
                cursor: { line: 0, ch: 0 },
                keys: "G''",
            },
            {
                name: '`` should jump to position before last jump',
                content: 'line1\nline2\nline3\nline4\nline5',
                cursor: { line: 1, ch: 3 },
                keys: 'G``',
            },
        ],
    },
    {
        name: 'macros',
        cases: [
            {
                name: 'qa dd q @a should delete two lines',
                content: 'one\ntwo\nthree\nfour',
                cursor: { line: 0, ch: 0 },
                keys: 'qaddq@a',
            },
            {
                name: '2@a should replay macro twice',
                content: 'aaa\nbbb\nccc\nddd\neee',
                cursor: { line: 0, ch: 0 },
                keys: 'qaddq2@a',
            },
            {
                name: '@@ should replay last executed macro',
                content: 'one\ntwo\nthree\nfour',
                cursor: { line: 0, ch: 0 },
                keys: 'qaddq@a@@',
            },
            {
                name: 'qa x q 3@a should delete 4 chars total',
                content: 'abcdefgh',
                cursor: { line: 0, ch: 0 },
                keys: 'qaxq3@a',
            },
            {
                name: 'macro should record and replay insert',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'qaAworld\x1bq@a',
            },
        ],
    },
    {
        name: 'select-mode',
        cases: [
            {
                name: 'gh extends charwise and typing replaces',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ghllx\x1b',
            },
            {
                name: 'gH selects entire line and typing replaces',
                content: 'first\nsecond',
                cursor: { line: 0, ch: 0 },
                keys: 'gHx\x1b',
            },
            {
                name: 'gh + BS deletes selection',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ghll\x08',
            },
            {
                name: 'gh + Esc exits without change',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ghll\x1b',
            },
            {
                name: 'v then Ctrl-G toggles to select then type replaces',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'vll\x07x\x1b',
            },
        ],
    },
    {
        name: 'virtual-replace-mode',
        cases: [
            {
                name: 'gR replaces characters',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'gRxy\x1b',
            },
            {
                name: 'gR at EOL appends',
                content: 'hi',
                cursor: { line: 0, ch: 1 },
                keys: 'gRxyz\x1b',
            },
            {
                name: 'gR + BS restores original',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'gRx\x08\x1b',
            },
        ],
    },
    {
        name: 'ctrl-o-return',
        cases: [
            {
                name: 'Ctrl-O from insert returns to insert after motion',
                content: 'hello world foo',
                cursor: { line: 0, ch: 0 },
                keys: 'i\x0fw\x1b',
            },
            {
                name: 'Ctrl-O from replace returns to replace then types',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'R\x0flx\x1b',
            },
        ],
    },
    {
        name: 'lua-keymaps',
        cases: [
            {
                name: 'lua nmap deletes line with Q',
                content: 'hello\nworld\nfoo',
                cursor: { line: 0, ch: 0 },
                keys: 'Q',
                luaSetup: "vim.keymap.set('n', 'Q', 'dd')",
            },
            {
                name: 'lua nmap X deletes line',
                content: 'aaa\nbbb\nccc',
                cursor: { line: 0, ch: 0 },
                keys: 'X',
                luaSetup: "vim.keymap.set('n', 'X', 'dd')",
            },
            {
                name: 'lua imap jk exits insert mode',
                content: 'hello',
                cursor: { line: 0, ch: 5 },
                keys: 'ajk',
                luaSetup: "vim.keymap.set('i', 'jk', '<Esc>')",
            },
            {
                name: 'lua nmap with noremap default (dd not recursive)',
                content: 'line1\nline2\nline3',
                cursor: { line: 1, ch: 0 },
                keys: 'Z',
                luaSetup: "vim.keymap.set('n', 'Z', 'dd')",
            },
            {
                name: 'lua nmap with remap=true makes recursive mapping',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'Z',
                luaSetup:
                    "vim.keymap.set('n', 'Y', 'dd'); vim.keymap.set('n', 'Z', 'Y', { remap = true })",
            },
            {
                name: 'lua keymap.del removes mapping',
                content: 'first\nsecond\nthird',
                cursor: { line: 0, ch: 0 },
                keys: 'Q',
                luaSetup:
                    "vim.keymap.set('n', 'Q', 'dd'); vim.keymap.del('n', 'Q')",
            },
            {
                name: 'lua nmap change word',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'Zfoo<Esc>',
                luaSetup: "vim.keymap.set('n', 'Z', 'cw')",
            },
            {
                name: 'lua nmap join lines',
                content: 'line1\nline2\nline3',
                cursor: { line: 0, ch: 0 },
                keys: 'Z',
                luaSetup: "vim.keymap.set('n', 'Z', 'J')",
            },
            {
                name: 'lua nmap yank word and paste',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ZWP',
                luaSetup: "vim.keymap.set('n', 'Z', 'yw')",
            },
            {
                name: 'lua vmap surrounds with parens',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'vlllZ',
                luaSetup: "vim.keymap.set('v', 'Z', 'c()<Esc>P')",
            },
            {
                name: 'lua multi-mode mapping (n and v)',
                content: 'first\nsecond',
                cursor: { line: 0, ch: 0 },
                keys: 'Z',
                luaSetup: "vim.keymap.set({'n', 'v'}, 'Z', 'dd')",
            },
            {
                name: 'lua leader key mapping',
                content: 'delete me\nkeep me',
                cursor: { line: 0, ch: 0 },
                keys: ' d',
                luaSetup:
                    "vim.g.mapleader = ' '; vim.keymap.set('n', '<leader>d', 'dd')",
            },
        ],
    },
];
