export interface TestCaseDefinition {
    name: string;
    content: string;
    cursor: { line: number; ch: number };
    keys: string;
}

export interface SuiteDefinition {
    name: string;
    cases: TestCaseDefinition[];
}

export const SUITES: SuiteDefinition[] = [
    {
        name: 'normal-motions',
        cases: [
            {
                name: 'h should move cursor left',
                content: 'abcdef',
                cursor: { line: 0, ch: 3 },
                keys: 'h',
            },
            {
                name: 'l should move cursor right',
                content: 'abcdef',
                cursor: { line: 0, ch: 1 },
                keys: 'l',
            },
            {
                name: 'j should move cursor down',
                content: 'line1\nline2\nline3',
                cursor: { line: 0, ch: 0 },
                keys: 'j',
            },
            {
                name: 'k should move cursor up',
                content: 'line1\nline2\nline3',
                cursor: { line: 2, ch: 0 },
                keys: 'k',
            },
            {
                name: '3j should move 3 lines down',
                content: 'a\nb\nc\nd\ne',
                cursor: { line: 0, ch: 0 },
                keys: '3j',
            },
            {
                name: 'w should move to next word start',
                content: 'hello world foo',
                cursor: { line: 0, ch: 0 },
                keys: 'w',
            },
            {
                name: 'b should move to previous word start',
                content: 'hello world foo',
                cursor: { line: 0, ch: 8 },
                keys: 'b',
            },
            {
                name: 'e should move to end of word',
                content: 'hello world foo',
                cursor: { line: 0, ch: 0 },
                keys: 'e',
            },
            {
                name: 'W should move to next WORD start',
                content: 'hello-world foo',
                cursor: { line: 0, ch: 0 },
                keys: 'W',
            },
            {
                name: 'B should move to previous WORD start',
                content: 'foo hello-world bar',
                cursor: { line: 0, ch: 15 },
                keys: 'B',
            },
            {
                name: 'E should move to end of WORD',
                content: 'hello-world foo',
                cursor: { line: 0, ch: 0 },
                keys: 'E',
            },
            {
                name: 'ge should move to end of previous word',
                content: 'hello world foo',
                cursor: { line: 0, ch: 6 },
                keys: 'ge',
            },
            {
                name: '2w should move 2 words forward',
                content: 'one two three four',
                cursor: { line: 0, ch: 0 },
                keys: '2w',
            },
            {
                name: 'w across empty lines',
                content: 'one\n\n\nfour',
                cursor: { line: 0, ch: 0 },
                keys: 'w',
            },
            {
                name: 'w with punctuation boundary',
                content: 'word.other',
                cursor: { line: 0, ch: 0 },
                keys: 'w',
            },
            {
                name: 'w should wrap to next line',
                content: 'one\ntwo',
                cursor: { line: 0, ch: 2 },
                keys: 'w',
            },
            {
                name: 'b at start of document should not move',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'b',
            },
            {
                name: 'w from punctuation to next word',
                content: 'word.other',
                cursor: { line: 0, ch: 4 },
                keys: 'w',
            },
            {
                name: 'b should stop at punctuation boundary',
                content: 'word.other',
                cursor: { line: 0, ch: 5 },
                keys: 'b',
            },
            {
                name: 'ge across line boundary',
                content: 'one\ntwo',
                cursor: { line: 1, ch: 0 },
                keys: 'ge',
            },
            {
                name: 'e should cross line boundary',
                content: 'one\ntwo',
                cursor: { line: 0, ch: 2 },
                keys: 'e',
            },
            {
                name: '0 should move to first column',
                content: '  hello world',
                cursor: { line: 0, ch: 5 },
                keys: '0',
            },
            {
                name: '$ should move to end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: '$',
            },
            {
                name: '^ should move to first non-blank',
                content: '   hello world',
                cursor: { line: 0, ch: 0 },
                keys: '^',
            },
            {
                name: '_ should move to first non-blank',
                content: '  one\n  two\n  three',
                cursor: { line: 0, ch: 0 },
                keys: '_',
            },
            {
                name: '$ with count',
                content: 'one\ntwo\nthree',
                cursor: { line: 0, ch: 0 },
                keys: '2$',
            },
            {
                name: '+ should move to next line non-blank',
                content: '  one\n  two\n  three',
                cursor: { line: 0, ch: 0 },
                keys: '+',
            },
            {
                name: '- should move to prev line non-blank',
                content: '  one\n  two\n  three',
                cursor: { line: 2, ch: 4 },
                keys: '-',
            },
            {
                name: 'G should move to last line',
                content: 'one\ntwo\nthree\nfour\nfive',
                cursor: { line: 0, ch: 0 },
                keys: 'G',
            },
            {
                name: 'gg should move to first line',
                content: 'one\ntwo\nthree\nfour\nfive',
                cursor: { line: 4, ch: 0 },
                keys: 'gg',
            },
            {
                name: '3G should move to line 3',
                content: 'one\ntwo\nthree\nfour\nfive',
                cursor: { line: 0, ch: 0 },
                keys: '3G',
            },
            {
                name: '5gg should move to line 5',
                content: 'a\nb\nc\nd\ne\nf\ng',
                cursor: { line: 0, ch: 0 },
                keys: '5gg',
            },
            {
                name: '| should move to column 1',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: '|',
            },
            {
                name: '5| should move to column 5',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: '5|',
            },
        ],
    },
    {
        name: 'normal-search',
        cases: [
            {
                name: 'f should find char to the right',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'fw',
            },
            {
                name: 'F should find char to the left',
                content: 'hello world',
                cursor: { line: 0, ch: 10 },
                keys: 'Fo',
            },
            {
                name: 't should move till before char',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'tw',
            },
            {
                name: 'T should move till after char',
                content: 'hello world',
                cursor: { line: 0, ch: 10 },
                keys: 'To',
            },
            {
                name: '2f should find second occurrence',
                content: 'abacada',
                cursor: { line: 0, ch: 0 },
                keys: '2fa',
            },
            {
                name: 'f should not move when char not found',
                content: 'abcdef',
                cursor: { line: 0, ch: 0 },
                keys: 'fz',
            },
            {
                name: 'f should not cross line boundary',
                content: 'abc\ndef',
                cursor: { line: 0, ch: 0 },
                keys: 'fe',
            },
            {
                name: 't should stop one char before target',
                content: 'abcdef',
                cursor: { line: 0, ch: 0 },
                keys: 'td',
            },
            {
                name: 'T should stop one char after target',
                content: 'abcdef',
                cursor: { line: 0, ch: 5 },
                keys: 'Tc',
            },
            {
                name: '2t should find second and stop before',
                content: 'axbxcxd',
                cursor: { line: 0, ch: 0 },
                keys: '2tx',
            },
            {
                name: 'F should not move when char not found',
                content: 'abcdef',
                cursor: { line: 0, ch: 5 },
                keys: 'Fz',
            },
            {
                name: '2F should find second backward',
                content: 'axbxcxd',
                cursor: { line: 0, ch: 6 },
                keys: '2Fx',
            },
        ],
    },
    {
        name: 'normal-marks-jumps',
        cases: [
            {
                name: '} should move to next empty line',
                content: 'line1\nline2\n\nline4\nline5',
                cursor: { line: 0, ch: 0 },
                keys: '}',
            },
            {
                name: '{ should move to previous empty line',
                content: 'line1\nline2\n\nline4\nline5',
                cursor: { line: 4, ch: 0 },
                keys: '{',
            },
            {
                name: '2} should move 2 paragraphs forward',
                content: 'a\n\nb\n\nc',
                cursor: { line: 0, ch: 0 },
                keys: '2}',
            },
            {
                name: '} at end should not move',
                content: 'a\n\nb',
                cursor: { line: 2, ch: 0 },
                keys: '}',
            },
            {
                name: '{ at start should not move',
                content: 'a\n\nb',
                cursor: { line: 0, ch: 0 },
                keys: '{',
            },
            {
                name: '2{ should move 2 paragraphs backward',
                content: 'a\n\nb\n\nc',
                cursor: { line: 4, ch: 0 },
                keys: '2{',
            },
            {
                name: '% should jump to matching paren',
                content: '(hello world)',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
            {
                name: '% should jump back from closing paren',
                content: '(hello world)',
                cursor: { line: 0, ch: 12 },
                keys: '%',
            },
            {
                name: '% should work with curly braces',
                content: '{ code }',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
            {
                name: '% should work with square brackets',
                content: '[items]',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
            {
                name: '% across lines',
                content: '(\nhello\n)',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
            {
                name: '% with nested brackets',
                content: '(a(b)c)',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
            {
                name: '% on inner bracket',
                content: '(a(b)c)',
                cursor: { line: 0, ch: 2 },
                keys: '%',
            },
            {
                name: 'N after / search should go to previous match',
                content:
                    'word\n(word)\n{word\nword.\n\nword search\n}word\nword\nword',
                cursor: { line: 5, ch: 5 },
                keys: '/word\nN',
            },
        ],
    },
    {
        name: 'operator-combos',
        cases: [
            {
                name: 'dw should delete to next word',
                content: 'one two three',
                cursor: { line: 0, ch: 0 },
                keys: 'dw',
            },
            {
                name: 'd$ should delete to end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: 'd$',
            },
            {
                name: 'd0 should delete to start of line',
                content: 'hello world',
                cursor: { line: 0, ch: 6 },
                keys: 'd0',
            },
            {
                name: 'dj should delete current and next line',
                content: 'one\ntwo\nthree',
                cursor: { line: 0, ch: 0 },
                keys: 'dj',
            },
            {
                name: 'dw on last word should not delete newline',
                content: 'hello\nworld',
                cursor: { line: 0, ch: 0 },
                keys: 'dw',
            },
            {
                name: 'dw should delete whitespace',
                content: 'one   two',
                cursor: { line: 0, ch: 3 },
                keys: 'dw',
            },
            {
                name: 'dd on last line',
                content: 'one\ntwo',
                cursor: { line: 1, ch: 0 },
                keys: 'dd',
            },
            {
                name: 'dd on only line',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'dd',
            },
            {
                name: 'd2w should delete 2 words',
                content: 'one two three four',
                cursor: { line: 0, ch: 0 },
                keys: 'd2w',
            },
            {
                name: '2dd should delete 2 lines',
                content: 'one\ntwo\nthree\nfour',
                cursor: { line: 0, ch: 0 },
                keys: '2dd',
            },
            {
                name: 'D should delete to end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: 'D',
            },
            {
                name: 'dk should delete current and previous',
                content: 'one\ntwo\nthree',
                cursor: { line: 1, ch: 0 },
                keys: 'dk',
            },
            {
                name: 'de should delete to end of word',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'de',
            },
            {
                name: 'db should delete backward',
                content: 'hello world',
                cursor: { line: 0, ch: 8 },
                keys: 'db',
            },
            {
                name: 'd$ cursor in middle',
                content: 'abcdef',
                cursor: { line: 0, ch: 2 },
                keys: 'd$',
            },
            {
                name: 'd0 at start should not delete',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'd0',
            },
            {
                name: 'dgg should delete to start',
                content: 'one\ntwo\nthree\nfour',
                cursor: { line: 2, ch: 0 },
                keys: 'dgg',
            },
            {
                name: 'dfx should delete through char',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'dfo',
            },
            {
                name: 'dtx should delete up to char',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'dto',
            },
            {
                name: 'x should delete char under cursor',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'x',
            },
            {
                name: 'X should delete char before cursor',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'X',
            },
            {
                name: '3x should delete 3 chars',
                content: 'abcde',
                cursor: { line: 0, ch: 0 },
                keys: '3x',
            },
            {
                name: 'dd should delete current line',
                content: 'line1\nline2\nline3',
                cursor: { line: 1, ch: 0 },
                keys: 'dd',
            },
            {
                name: 'dd should preserve cursor column',
                content: '  hello\n  world\n  third',
                cursor: { line: 0, ch: 4 },
                keys: 'dd',
            },
            {
                name: '2dd should preserve cursor column',
                content: '  hello\n  world\n  third\n  fourth',
                cursor: { line: 0, ch: 3 },
                keys: '2dd',
            },
            {
                name: 'dj should preserve cursor column',
                content: '  aaa\n  bbb\n  ccc',
                cursor: { line: 0, ch: 4 },
                keys: 'dj',
            },
            {
                name: 'dk should preserve cursor column',
                content: '  aaa\n  bbb\n  ccc',
                cursor: { line: 1, ch: 4 },
                keys: 'dk',
            },
            {
                name: 'dd should clamp column to shorter line',
                content: 'long line here\nhi\nthird',
                cursor: { line: 0, ch: 10 },
                keys: 'dd',
            },
            {
                name: 'J should join lines with space',
                content: 'hello\nworld',
                cursor: { line: 0, ch: 0 },
                keys: 'J',
            },
            {
                name: 'J should strip trailing whitespace before join',
                content: 'hello \n    world',
                cursor: { line: 0, ch: 0 },
                keys: 'J',
            },
            {
                name: 'J should strip leading whitespace from next line',
                content: 'hello\n    world',
                cursor: { line: 0, ch: 0 },
                keys: 'J',
            },
            {
                name: '3J should join 3 lines stripping whitespace',
                content: 'aaa \n  bbb\nccc',
                cursor: { line: 0, ch: 0 },
                keys: '3J',
            },
            {
                name: 'r should replace single char',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'rX',
            },
            {
                name: '>> should indent line',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: '>>',
            },
            {
                name: '<< should unindent line',
                content: '\thello',
                cursor: { line: 0, ch: 0 },
                keys: '<<',
            },
            {
                name: 'dw on empty line before whitespace should place cursor correctly',
                content: '\n  \nword',
                cursor: { line: 0, ch: 0 },
                keys: 'dw',
            },
            {
                name: 'd2w should delete across line boundary',
                content: ' word1\nword2',
                cursor: { line: 0, ch: 1 },
                keys: 'd2w',
            },
            {
                name: 'dge on empty lines should delete all',
                content: '\n\n',
                cursor: { line: 1, ch: 0 },
                keys: 'dge',
            },
            {
                name: 'db should delete across line boundary including whitespace',
                content: ' word1\nword2 ',
                cursor: { line: 1, ch: 0 },
                keys: 'db',
            },
            {
                name: '% should skip quoted brackets',
                content: '(a")"b)',
                cursor: { line: 0, ch: 0 },
                keys: '%',
            },
        ],
    },
    {
        name: 'text-objects-builtin',
        cases: [
            {
                name: 'diw should delete inner word',
                content: 'hello world foo',
                cursor: { line: 0, ch: 8 },
                keys: 'diw',
            },
            {
                name: 'daw should delete a word with space',
                content: 'hello world foo',
                cursor: { line: 0, ch: 6 },
                keys: 'daw',
            },
            {
                name: 'diW should delete inner WORD',
                content: 'hello foo-bar baz',
                cursor: { line: 0, ch: 8 },
                keys: 'diW',
            },
            {
                name: 'daW should delete a WORD with space',
                content: 'hello foo-bar baz',
                cursor: { line: 0, ch: 6 },
                keys: 'daW',
            },
            {
                name: 'di( should delete inside parens',
                content: 'call(arg1, arg2)',
                cursor: { line: 0, ch: 8 },
                keys: 'di(',
            },
            {
                name: 'da( should delete including parens',
                content: 'call(arg1, arg2) end',
                cursor: { line: 0, ch: 8 },
                keys: 'da(',
            },
            {
                name: 'di" should delete inside quotes',
                content: 'say "hello world" end',
                cursor: { line: 0, ch: 8 },
                keys: 'di"',
            },
            {
                name: 'da" should delete including quotes',
                content: 'say "hello world" end',
                cursor: { line: 0, ch: 8 },
                keys: 'da"',
            },
            {
                name: "di' should delete inside single quotes",
                content: "say 'hello' end",
                cursor: { line: 0, ch: 6 },
                keys: "di'",
            },
            {
                name: 'di{ should delete inside braces',
                content: 'obj{ key: val }',
                cursor: { line: 0, ch: 8 },
                keys: 'di{',
            },
            {
                name: 'da{ should delete including braces',
                content: 'obj{ key: val } end',
                cursor: { line: 0, ch: 8 },
                keys: 'da{',
            },
            {
                name: 'di[ should delete inside brackets',
                content: 'arr[1, 2, 3]',
                cursor: { line: 0, ch: 6 },
                keys: 'di[',
            },
            {
                name: 'diw on whitespace',
                content: 'hello   world',
                cursor: { line: 0, ch: 6 },
                keys: 'diw',
            },
            {
                name: 'daw at end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 6 },
                keys: 'daw',
            },
            {
                name: 'di( with nested parens',
                content: '(outer (inner) more)',
                cursor: { line: 0, ch: 10 },
                keys: 'di(',
            },
            {
                name: 'di( across lines',
                content: '(\nhello\n)',
                cursor: { line: 1, ch: 0 },
                keys: 'di(',
            },
            {
                name: 'di{ with nested braces',
                content: '{ outer { inner } more }',
                cursor: { line: 0, ch: 12 },
                keys: 'di{',
            },
            {
                name: 'di[ with nested brackets',
                content: '[outer [inner] more]',
                cursor: { line: 0, ch: 10 },
                keys: 'di[',
            },
            {
                name: 'diW with mixed punctuation',
                content: 'hello foo.bar,baz end',
                cursor: { line: 0, ch: 10 },
                keys: 'diW',
            },
            {
                name: 'd2aw should delete 2 words',
                content: 'one two three four',
                cursor: { line: 0, ch: 4 },
                keys: 'd2aw',
            },
        ],
    },
    {
        name: 'normal-editing',
        cases: [
            {
                name: 'x should delete char under cursor',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'x',
            },
            {
                name: 'X should delete char before cursor',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'X',
            },
            {
                name: '3x should delete 3 chars',
                content: 'abcde',
                cursor: { line: 0, ch: 0 },
                keys: '3x',
            },
            {
                name: 'dd should delete current line',
                content: 'line1\nline2\nline3',
                cursor: { line: 1, ch: 0 },
                keys: 'dd',
            },
            {
                name: 'D should delete to end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: 'D',
            },
            {
                name: '2dd should delete 2 lines',
                content: 'one\ntwo\nthree\nfour',
                cursor: { line: 1, ch: 0 },
                keys: '2dd',
            },
            {
                name: 'dw should delete word',
                content: 'hello world foo',
                cursor: { line: 0, ch: 0 },
                keys: 'dw',
            },
            {
                name: 'cc should change entire line',
                content: 'old text\nkeep this',
                cursor: { line: 0, ch: 0 },
                keys: 'ccnew\x1b',
            },
            {
                name: 'C should change to end of line',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: 'C!\x1b',
            },
            {
                name: 'cw should change word',
                content: 'old new end',
                cursor: { line: 0, ch: 0 },
                keys: 'cwrep\x1b',
            },
            {
                name: 's should substitute char',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'sX\x1b',
            },
            {
                name: 'S should substitute entire line',
                content: 'old line\nkeep',
                cursor: { line: 0, ch: 3 },
                keys: 'Snew\x1b',
            },
            {
                name: 'r should replace single char',
                content: 'abcde',
                cursor: { line: 0, ch: 2 },
                keys: 'rX',
            },
            {
                name: 'R should enter replace mode',
                content: 'abcde',
                cursor: { line: 0, ch: 0 },
                keys: 'RXY\x1b',
            },
            {
                name: 'J should join lines with space',
                content: 'hello\nworld',
                cursor: { line: 0, ch: 0 },
                keys: 'J',
            },
            {
                name: '~ should toggle case',
                content: 'Hello',
                cursor: { line: 0, ch: 0 },
                keys: '~',
            },
            {
                name: 'u should undo last change',
                content: 'original',
                cursor: { line: 0, ch: 0 },
                keys: 'ddu',
            },
            {
                name: '. should repeat dd',
                content: 'aaa\nbbb\nccc',
                cursor: { line: 0, ch: 0 },
                keys: 'dd.',
            },
            {
                name: '. should repeat dw',
                content: 'one two three four',
                cursor: { line: 0, ch: 0 },
                keys: 'dw.',
            },
            {
                name: '3. should repeat with count',
                content: 'abcde',
                cursor: { line: 0, ch: 0 },
                keys: 'x3.',
            },
            {
                name: '. should repeat cw with text',
                content: 'old old old',
                cursor: { line: 0, ch: 0 },
                keys: 'cwnew \x1bw.',
            },
        ],
    },
    {
        name: 'normal-yank-put',
        cases: [
            {
                name: 'yy then p should paste line below',
                content: 'hello world\nsecond line',
                cursor: { line: 0, ch: 0 },
                keys: 'yyp',
            },
            {
                name: 'dd then p should paste deleted line below',
                content: 'first\nsecond\nthird',
                cursor: { line: 0, ch: 0 },
                keys: 'ddp',
            },
            {
                name: 'yw then p should paste word',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'yw$p',
            },
            {
                name: 'P should paste before cursor',
                content: 'world',
                cursor: { line: 0, ch: 0 },
                keys: 'yw0P',
            },
            {
                name: '"ayy then "ap should paste from register a',
                content: 'alpha line\nbeta line',
                cursor: { line: 0, ch: 0 },
                keys: '"ayyG"ap',
            },
            {
                name: 'y$ should yank to end without newline',
                content: 'hello world\nsecond',
                cursor: { line: 0, ch: 6 },
                keys: 'y$jp',
            },
            {
                name: '2yy then p should paste 2 lines',
                content: 'one\ntwo\nthree',
                cursor: { line: 0, ch: 0 },
                keys: '2yyGp',
            },
        ],
    },
    {
        name: 'normal-insert-entry',
        cases: [
            {
                name: 'i should insert text before cursor',
                content: 'hello',
                cursor: { line: 0, ch: 2 },
                keys: 'iX\x1b',
            },
            {
                name: 'a should insert text after cursor',
                content: 'hello',
                cursor: { line: 0, ch: 2 },
                keys: 'aX\x1b',
            },
            {
                name: 'I should insert at first non-blank',
                content: '  hello',
                cursor: { line: 0, ch: 4 },
                keys: 'IX\x1b',
            },
            {
                name: 'A should append at end of line',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'A!\x1b',
            },
            {
                name: 'o should open line below',
                content: 'line1\nline2',
                cursor: { line: 0, ch: 0 },
                keys: 'onew\x1b',
            },
            {
                name: 'O should open line above',
                content: 'line1\nline2',
                cursor: { line: 1, ch: 0 },
                keys: 'Onew\x1b',
            },
        ],
    },
    {
        name: 'visual-mode',
        cases: [
            {
                name: 'v + e + d should delete selection',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'ved',
            },
            {
                name: 'V + d should delete entire line',
                content: 'line1\nline2\nline3',
                cursor: { line: 1, ch: 0 },
                keys: 'Vd',
            },
            {
                name: 'V + j + d should delete multiple lines',
                content: 'one\ntwo\nthree\nfour',
                cursor: { line: 1, ch: 0 },
                keys: 'Vjd',
            },
            {
                name: 'v + iw + d should delete word',
                content: 'hello world foo',
                cursor: { line: 0, ch: 7 },
                keys: 'viwd',
            },
            {
                name: 'v + 3l + d should delete 4 chars',
                content: 'abcdefgh',
                cursor: { line: 0, ch: 0 },
                keys: 'v3ld',
            },
            {
                name: 'V + > should indent line',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'V>',
            },
            {
                name: 'V + J should join selected lines',
                content: 'line one\nline two\nline three',
                cursor: { line: 0, ch: 0 },
                keys: 'VjJ',
            },
        ],
    },
    {
        name: 'g-commands',
        cases: [
            {
                name: 'gj should move one display line down',
                content: 'short\nline two',
                cursor: { line: 0, ch: 0 },
                keys: 'gj',
            },
            {
                name: 'gk should move one display line up',
                content: 'line one\nshort',
                cursor: { line: 1, ch: 0 },
                keys: 'gk',
            },
            {
                name: 'g0 should move to start of display line',
                content: 'hello world',
                cursor: { line: 0, ch: 5 },
                keys: 'g0',
            },
            {
                name: 'g$ should move to end of display line',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'g$',
            },
            {
                name: 'guu should lowercase entire line',
                content: 'HELLO WORLD',
                cursor: { line: 0, ch: 0 },
                keys: 'guu',
            },
            {
                name: 'gUU should uppercase entire line',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'gUU',
            },
            {
                name: 'guw should lowercase word',
                content: 'HELLO world',
                cursor: { line: 0, ch: 0 },
                keys: 'guw',
            },
            {
                name: 'gUw should uppercase word',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: 'gUw',
            },
            {
                name: 'g~~ should toggle case of line',
                content: 'Hello World',
                cursor: { line: 0, ch: 0 },
                keys: 'g~~',
            },
            {
                name: 'gI should insert at column 0',
                content: '  hello',
                cursor: { line: 0, ch: 4 },
                keys: 'gIX\x1b',
            },
            {
                name: 'gJ should join lines without space',
                content: 'hello\nworld',
                cursor: { line: 0, ch: 0 },
                keys: 'gJ',
            },
            {
                name: 'ga should not move cursor',
                content: 'Hello',
                cursor: { line: 0, ch: 0 },
                keys: 'ga',
            },
            {
                name: 'gqq should reformat current line',
                content: 'short line here',
                cursor: { line: 0, ch: 0 },
                keys: 'gqq',
            },
            {
                name: 'Vgq should reformat selected line',
                content: 'short line here',
                cursor: { line: 0, ch: 0 },
                keys: 'Vgq',
            },
            {
                name: 'gqj should reformat current and next line',
                content: 'short line one\nshort line two',
                cursor: { line: 0, ch: 0 },
                keys: 'gqj',
            },
        ],
    },
    {
        name: 'bracket-commands',
        cases: [
            {
                name: '[( should jump to previous unmatched (',
                content: '(hello (world) end)',
                cursor: { line: 0, ch: 10 },
                keys: '[(',
            },
            {
                name: ']) should jump to next unmatched )',
                content: '(hello (world) end)',
                cursor: { line: 0, ch: 10 },
                keys: '])',
            },
            {
                name: '[{ should jump to previous unmatched {',
                content: '{ outer { inner } end }',
                cursor: { line: 0, ch: 12 },
                keys: '[{',
            },
            {
                name: ']} should jump to next unmatched }',
                content: '{ outer { inner } end }',
                cursor: { line: 0, ch: 12 },
                keys: ']}',
            },
        ],
    },
    {
        name: 'insert-mode',
        cases: [
            {
                name: 'Escape from insert should allow x to delete',
                content: 'hello',
                cursor: { line: 0, ch: 0 },
                keys: 'i\x1bx',
            },
            {
                name: 'Ctrl-W should delete word in insert',
                content: '',
                cursor: { line: 0, ch: 0 },
                keys: 'ihello world\x17\x1b',
            },
            {
                name: 'Ctrl-U should delete to start in insert',
                content: '',
                cursor: { line: 0, ch: 0 },
                keys: 'ihello\x15\x1b',
            },
            {
                name: 'Ctrl-O should execute one normal command',
                content: 'hello\nworld',
                cursor: { line: 1, ch: 0 },
                keys: 'i\x0fk\x1b',
            },
        ],
    },
    {
        name: 'normal-scroll',
        cases: [
            {
                name: 'Ctrl-A should increment number',
                content: 'count: 5',
                cursor: { line: 0, ch: 7 },
                keys: '\x01',
            },
            {
                name: 'Ctrl-X should decrement number',
                content: 'count: 5',
                cursor: { line: 0, ch: 7 },
                keys: '\x18',
            },
        ],
    },
    {
        name: 'ex-commands-builtin',
        cases: [
            {
                name: ':s/old/new/ should replace first on line',
                content: 'old old old',
                cursor: { line: 0, ch: 0 },
                keys: ':s/old/new/\n',
            },
            {
                name: ':s/old/new/g should replace all on line',
                content: 'old old old',
                cursor: { line: 0, ch: 0 },
                keys: ':s/old/new/g\n',
            },
            {
                name: ':sort should sort lines',
                content: 'cherry\napple\nbanana',
                cursor: { line: 0, ch: 0 },
                keys: ':sort\n',
            },
            {
                name: ':d should delete current line',
                content: 'one\ntwo\nthree',
                cursor: { line: 1, ch: 0 },
                keys: ':d\n',
            },
        ],
    },
    {
        name: 'ex-commands-expanded',
        cases: [
            {
                name: ':yank should not error',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: ':yank\n',
            },
            {
                name: ':join should join lines',
                content: 'one\ntwo\nthree',
                cursor: { line: 0, ch: 0 },
                keys: ':join\n',
            },
            {
                name: ':nohlsearch should not error',
                content: 'hello world',
                cursor: { line: 0, ch: 0 },
                keys: ':nohlsearch\n',
            },
            {
                name: ':undo should undo',
                content: 'original',
                cursor: { line: 0, ch: 0 },
                keys: 'dd\n:undo\n',
            },
            {
                name: ':redo should redo',
                content: 'original',
                cursor: { line: 0, ch: 0 },
                keys: 'ddu\n:redo\n',
            },
            {
                name: ':global should execute on matching lines',
                content: 'keep\nremove\nkeep\nremove',
                cursor: { line: 0, ch: 0 },
                keys: ':g/remove/d\n',
            },
        ],
    },
];
